services:
  sabine:
    build: 
      context: .
      dockerfile: apps/sabine/Dockerfile
      secrets:
        - env
    image: sabine
    container_name: sabine
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - apps/sabine/.env
    environment:
      - REDIS_URL=redis://localhost:6379
      - NODE_ENV=production
    network_mode: host

  helper:
    build: 
      context: .
      dockerfile: apps/helper/Dockerfile
      secrets:
        - env
    image: sabine-helper
    container_name: sabine-helper
    restart: unless-stopped
    env_file:
      - apps/helper/.env
    network_mode: host

  web:
    build: 
      context: .
      dockerfile: apps/web/Dockerfile
      secrets:
        - env
    image: sabine-website
    container_name: sabine-website
    restart: always
    env_file:
      - apps/web/.env
    network_mode: host  

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    network_mode: host
    command: redis-server --bind localhost
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli replicaof no one && redis-cli ping']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:

secrets:
  env:
    file: ./.env